CREATE TABLE VETERINARIANS(
VETNAME VARCHAR2(10),
LICENSENUM INTEGER,
PRIMARY KEY(LICENSENUM))

CREATE TABLE DOGS(
DOGNAME VARCHAR2(10),
DID INTEGER,
PRIMARY KEY(DID))

CREATE TABLE LOCATION(
LID INTEGER,
LOCNAME VARCHAR2(15),
PRIMARY KEY(LID))

CREATE TABLE EXAMINE(
LICENSENUM INTEGER,
DID INTEGER,
LID INTEGER,
FEE INTEGER,
FOREIGN KEY(LICENSENUM) REFERENCES VETERINARIANS,
FOREIGN KEY(DID) REFERENCES DOGS,
FOREIGN KEY(LID) REFERENCES LOCATION )