CREATE OR REPLACE PROCEDURE NUM_OF_LOC(NAMEOFDOG IN VARCHAR2) AS
NDOGLOC INTEGER;
BEGIN 
SELECT DISTINCT COUNT(LOCNAME) INTO NDOGLOC
FROM LOCATION L, EXAMINE E, DOGS D
WHERE L.LID = E.LID AND E.DID = D.DID
AND D.DOGNAME = NAMEOFDOG;
DBMS_OUTPUT.PUT('NUMBER OF LOCATIONS ='||NDOGLOC);
END;


create or replace PROCEDURE SUM_OF_FEES(VETERIANNAME IN VARCHAR2, DOGEXAM_LOC IN VARCHAR2) AS
SUM_FEES INTEGER;
BEGIN 
    SELECT coalesce (SUM(E.FEE),0)INTO SUM_FEES
    FROM VETERINARIANS V, EXAMINE E, LOCATION L
    WHERE V.VETNAME = VETERIANNAME 
    AND V.LICENSENUM = E.LICENSENUM
    AND E.LID = L.LID
    AND L.LOCNAME = DOGEXAM_LOC;
    DBMS_OUTPUT.PUT_LINE('SUM OF FEES THAT VETERINARIAN '||VETERIANNAME||' EARNED AT LOCATION '||DOGEXAM_LOC||' IS '||SUM_FEES);
END;